### ISSUE TITLE
Clean up the API of `SourceGenFromSpec.generateSourceInDir`

### ISSUE THREAD

**Issue by nresare** [goldmansachs/crdtools#17]
The signature and semantics of `SourceGenFromSpec.generateSourceInDir()` are a bit strange, I think it could be improved.

Some things I find strange:

* The name of the method. I read generateSourceInDir() as "generate source, but do it in a specific dir". To do things in a directory, I would assume, means do it with a process that has it's current working directory (CWD) set to some specific directory. This does not make sense in this context.
* The temporary directory to use for output seems to me like an implementation detail, and could be hidden away from the user. 
* RuntimeExceptions are not checked and don't need to be declared in the throws statement
* The docs doesn't specify what the format of the output is, only that it will be written to a path

**Comment by alfredomusumeci** [comment]
Solved at https://github.com/goldmansachs/crdtools/pull/21
