### ISSUE TITLE
Make extractSpecs() more flexible

### ISSUE THREAD

**Issue by nresare** [goldmansachs/crdtools#18]
`SourceGenFromSpec.extractSpecs()` implements a transform of a general purpose data structure (CRD) into another data structure (a valid openapi 3.0 specification). This is functionality that lends itself well to unit testing and can be used for all kinds of input. However, the method hard codes its input as the thing returned from `getCrdsYaml()`.

Modify the method such that it specifies input and output as parameters, instead of having the input be hard coded.

**Comment by alfredomusumeci** [comment]
Solved at https://github.com/goldmansachs/crdtools/pull/22
