### ISSUE TITLE
Avoid creating a temporary file with the openapi spec yaml

### ISSUE THREAD

**Issue by nresare** [goldmansachs/crdtools#19]
The code currently generates an openapi spec yaml as a temporary file on disk from the input crd, which is then passed to the swagger codegen configurator. I think it would be neater if we could avoid the temporary file (and thus avoid the need to figure out where it should be put, making sure that it is cleaned up and so on) and instead generate the yaml into a string and pass it to swagger in this form.

**Comment by alfredomusumeci** [comment]
Resolved at https://github.com/goldmansachs/crdtools/pull/20

**Comment by alfredomusumeci** [comment]
Addressed at https://github.com/alfredomusumeci/crdtools/pull/3
