### ISSUE TITLE
Have `pullOpenapiSpecs` be smarter about which version to pick

### ISSUE THREAD

**Issue by nresare** [goldmansachs/crdtools#27]
A crd can (and often does) contain different versions of the models. Right now we just pick the first one, regardless of which one is the latest one. It would be better if we picked the one that has `storage: true` as a property when generating the openapi spec.

**Comment by alfredomusumeci** [comment]
Solved at https://github.com/goldmansachs/crdtools/pull/30/commits/f98ed596660b0a644cb557add65ce858fc5ca619
