### ISSUE TITLE
Have `pullOpenapiSpecs` return group and version as well as openapi specs

### ISSUE THREAD

**Issue by nresare** [goldmansachs/crdtools#28]
Besides the openapi spec we need the group and version from the crd, to be able to correctly generate the annotation in the generated models. Let's return a record instead of a String from pullOpenapiSpecs, containing all 3 of the pieces of information needed.

**Comment by alfredomusumeci** [comment]
Addressed at https://github.com/goldmansachs/crdtools/pull/36
