### ISSUE TITLE
Migrate //kccapi:spec to this repository

### ISSUE THREAD

**Issue by nresare** [goldmansachs/crdtools#4]
The `//kccapi:spec` target can be built in the monorepo. Migrate the code needed to be able to run this target in this project instead. When this is done, it should be possible to run `bazel build //:spec` in this repository, generating an output file that is equal to the file available as `bazel-bin/kccapi/all-specs.yaml` after having run `bazel build //kccapi:spec`

**Comment by alfredomusumeci** [comment]
Migration completed, awaiting review

**Comment by nresare** [comment]
This has been done
