### ISSUE TITLE
Field type changed from long to integer

### ISSUE THREAD

**Issue by nresare** [goldmansachs/crdtools#56]
When generating classes from the [kccapi upstream crds.yaml](https://github.com/GoogleCloudPlatform/k8s-config-connector/blob/master/install-bundles/install-bundle-workload-identity/crds.yaml) the generated class StorgeBucketSpecCondition used to have a field `age` with the type Long. Now the same field has the type Integer.

Figure out why this is, and come up with a plan to reconcile this (either have crdtools behave as the old implementation, or update the call sites to use the new implementation)

**Comment by alfredomusumeci** [comment]
https://github.com/goldmansachs/crdtools/pull/57 closes this
