### ISSUE TITLE
Combine :openapi-src-genner and :spec into single binary

### ISSUE THREAD

**Issue by nresare** [goldmansachs/crdtools#6]
It would make sense to have a single main method that can be used to connect these two pieces of functionality (generate openapi-v3 spec from crd, and generate java from openapiv3 spec) into a single operation

**Comment by alfredomusumeci** [comment]
This task has been completed and a pull request has been submitted.

**Comment by nresare** [comment]
Landed as of the merging of https://github.com/goldmansachs/crdtools/pull/13
