### ISSUE TITLE
move away from using io.swagger.codegen.v3:swagger-codegen-cli

### ISSUE THREAD

**Issue by nresare** [goldmansachs/crdtools#7]
The io.swagger.codegen.v3:swagger-codegen-cli library is built to be able to be used as as single dependency, where everything is baked in such that it can be used as a single jar. This is a bit inconvenient for us, it would be neater to figure out and possibly replicate what swagger-codegen-cli does using swagger-codegen instead.

**Comment by alfredomusumeci** [comment]
Pull request at https://github.com/goldmansachs/crdtools/pull/13

**Comment by nresare** [comment]
This has been resolved as of the merging of https://github.com/goldmansachs/crdtools/pull/13
