### ISSUE TITLE
Investigate possibility to add custom fields to generated classes

### ISSUE THREAD

**Issue by nresare** [goldmansachs/crdtools#8]
I don't know whether it is a feature of swagger codegen to add stuff to the generated java code, but it would be very valuable to add information in some way to the generated classes that is needed to be able to generate yaml from instances. Right now, there are some pieces of information in ToYaml.java (The `Kind` enum) that needs to be updated as soon as one adds a new piece of functionality.

**Comment by alfredomusumeci** [comment]
This has been addressed by adding a custom annotation, see https://github.com/goldmansachs/crdtools/pull/38
